name: goreleaser

on:
  push:
    # run only against tags on main
    tags:
      - "v*"
permissions:
  contents: write
  packages: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/c